### PR TITLE
Keep It Simple - remove JavaScript build environment

### PR DESCRIPTION
**Pull request by tobinus**
The JavaScript build environment did in reality just two things: it added Skeleton, and it minified the HTML and CSS. This pull requests moves away from a JavaScript build environment, replacing it with a dead simple webroot which can be instantly deployed, with no fuss. This is done by including the Skeleton library inside the repository (the licenses are compatible). The lack of minified CSS and HTML is not really a problem (gzip and caching come to the rescue :P ).

The reason for not wanting a full-stack JavaScript environment is that its impact on readability of the code and modifiability (due to simplifying inclusion of libraries and compilation from less to CSS) does not weight
up for the hit on modifiability (due to the complexity of setting this up, especially if you're not developing JavaScript apps day by day) and ease of deployment (requiring you to basically have a development environment just to push out a small change). The last two points are important, especially since this project is "maintained by IT-drift", which do not really work on JavaScript apps normally. This web page is very simple, the use of less had no impact whatsoever, and the use of JavaScript Webpack, bower etc. complicates things much more than they help. If the web page used React, was interactive, greatly benefited from using less or something along those lines, the JavaScript stack would be much more appropriate imo :)

### CODE REVIEW

**Comment by tobinus** [comment]
This branch probably has conflicts with my other PR, but once one is merged, I can volunteer to fix those merge conflicts :)

**Comment by jornane** [comment]
:+1: :clap: :1st_place_medal: LGTM

**Comment by nerok** [comment]
<3

**Comment by essoen** [comment]
Great! 
I agree, the reason for the environment was really just out of convenience at the time.

Studentmediene.no might need such an environment, as we need to implement some sort of system that enables the board to publish their meeting minutes. It's not decided how that's to be done yet.

**Pull request merged**
