### PR TITLE
Add radioservices, add radio as a product

### PR DESCRIPTION
**Pull request by tobinus**
The heading for editorial services has been split so that video and text share one section, and radio has a section of its own.

### CODE REVIEW

**Comment by essoen** [comment]
Small problem with the formatting (See "Skryt")

image

Trying to find the cause

**Comment by tobinus** [comment]
Problem with formatting seems to be that Booking starts a new row, and Skryt! then must start a new row. Perhaps it could be fixed by using rows?

**Comment by essoen** [comment]
Hm, I suggest we place the Radio-services under "Reakdsjonelt", and give some good explanations. Or i can override the CSS framework and make the site wider. In any case, I think we want the radioservices higher on the site.  What do you think?

**Comment by tobinus** [comment]
Agreed, it's a bit awkward to scroll that far. I suggest we go with your first suggestion. Shall you or shall I? :)

**Comment by essoen** [comment]
I worked a bit with the formatting. How about this?
image

Maybe I should move Kapina up so it's between Momus and Chimera?

**Comment by tobinus** [comment]
Looks alright. However, the content under each heading no longer has more indentation than the heading, making them look less like headings.

**Comment by santi** [comment]
If you want to fix the original problem, look here:
http://stackoverflow.com/questions/8822222

Med vennlig hilsen,
Vemund M Santi
+47 918 89 863

**Comment by tobinus** [comment]
I took the liberty of duplicating some of the sketching you had done, @essoen. I believe this resolves both the issue of screen space usage, and the weird bug you mentioned in your first comment (happened since columns for different rows appeared inside the same `<div class="row">`), so it is pretty close to the screen shot you offered. How does it look?

I'd like for smint.no to be updated in the not-so-distant future, since the radio specific links currently are not found anywhere other than our Confluence space (their previous location has been taken offline, since I thought this wouldn't take so long :P ).

**Comment by essoen** [comment]
Could you post a screenshot with the changes so one doesn't have to pull?

I'll take a look sometime this week myself

**Comment by tobinus** [comment]
I can do better than that ;) Have a look at http://folk.ntnu.no/twdahl/smint.no/webroot/

**Comment by essoen** [comment]
Nice. My only issue is that it looks weird to me when the grid is different at the bottom, but it's not a big issue =)

**Pull request merged**
