### PR TITLE
Update for spring 18

### PR DESCRIPTION
**Pull request by tobinus**
With some placeholders for services that are coming, and a new design.

Available at http://folk.ntnu.no/twdahl/smint.no/webroot/

### CODE REVIEW

**Review by nerok — APPROVED** [review]
Good job, I really like this

**Comment by tobinus** [comment]
Wait a moment, the Office 365 link is not working. I'll do a couple improvements while I'm at it.

**Comment by tobinus** [comment]
I consider myself done with this now. I've updated http://folk.ntnu.no/twdahl/smint.no/webroot/ again.

**Comment by nerok** [comment]
I like the new changes, still approve

**Comment by bendike** [comment]
Looks good. Approval.

**Review by halv00rsen — APPROVED** [review]
Good work bro

**Review by bendike — APPROVED** [review]
There we go

**Review by TheSimoms — APPROVED** [review]

**Review by mathialm — APPROVED** [review]
Looks good

**Comment by nerok** [comment]
Released [smint.no](https://www.smint.no)

**Pull request merged**
