### PR TITLE
Add orakel.smint.no

### PR DESCRIPTION
**Pull request by tobinus**

### CODE REVIEW

**Comment by tobinus** [comment]
Preview available at http://folk.ntnu.no/twdahl/smint.no/webroot/

**Review by nerok — APPROVED** [review]
Looks very nice, should maybe get a go ahead from @bendike that it is okay to remove the old error reporting link

**Comment by bendike** [comment]
👍🏼

**Comment by tobinus** [comment]
On request from @nerok I've created an identical pull request, except it does not remove the link to the faulty equipment report. That way, we can get up the link to orakel before the broadcast engineers have agreed to move the faulty equipment report to JIRA.

**Comment by tobinus** [comment]
I'll put up a new pull request once we have agreed to use JIRA instead.

**Pull request closed without merging**
